name: request_response_isolate
description: A simple Library to make the handling of global data syncing easier
version: 1.0.0
homepage: https://github.com/timoxd7/request_response_isolate

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  mutex: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
